# This is the configuration part of the makefile designed to be shared among
# other makefiles as required.

# ------------------------------------------------------------------------------
# List of symbols which can be defined in the CONFIG file

# Site definition for local configuration options
MUST_DEFINE += SITE

# FPGA build and simulation tools
MUST_DEFINE += VIVADO
MUST_DEFINE += VSIM

# Matlab C extension compiler
MUST_DEFINE += MEX

# EPICS support tools
MUST_DEFINE += EPICS_BASE
MUST_DEFINE += EPICS_DEVICE

# MTCA server followed by list of AMC IPs
MUST_DEFINE += AMC525_SERVER

# Driver group for amc525_mbf device nodes
MUST_DEFINE += DRV_GROUP


# The following defaults can be overridden in the CONFIG file

# Identifies license server for FPGA tools
LM_LICENSE_FILE =

PYTHON = python2

BUILD_DIR = $(MBF_TOP)/build
FPGA_BUILD_DIR = $(BUILD_DIR)/fpga
DRIVER_BUILD_DIR = $(BUILD_DIR)/driver
SIM_BUILD_DIR = $(BUILD_DIR)/sim

# Extra C compiler flags
CFLAGS_EXTRA =


# ------------------------------------------------------------------------------

# The following extremly tricksy makefile code converts the list of MUST_DEFINE
# names into symbols which will generate a suitable error when an attempt is
# made to expand them.  These will be defined in the CONFIG file.
define _MUST_DEFINE
ifndef $1
    $1 = $$(error Must define symbol $1 in CONFIG file)
endif
endef
_EVAL_MUST_DEFINE = $(eval $(_MUST_DEFINE))
$(foreach var,$(MUST_DEFINE),$(call _EVAL_MUST_DEFINE,$(var)))

include $(MBF_TOP)/CONFIG


PYTHONDIR = $(MBF_TOP)/AMC525/python

# Convert license file from space separate to : separated list
SPACE := $(subst ,, )
export LM_LICENSE_FILE := $(subst $(SPACE),:,$(LM_LICENSE_FILE))

# The default shell used by make is sh, but we may want to use the bash pipefail
# option.  On most systems this still works because sh is now usually linked to
# bash, but on Ubuntu sh is linked to dash which doesn't support pipefail.
# Setting this option is always safe, just makes bash an explicit dependency.
SHELL = bash
