[Unit]
Requires=amc525-firmware.service
After=amc525-firmware.service

[Service]
EnvironmentFile=
EnvironmentFile=/opt/host/.mbf-env

ExecStart=
ExecStart=/etc/systemd/system/script-esrf/host/starter-launcher.sh %H
