[Unit]
Requires=amc525-firmware.service
After=amc525-firmware.service

[Service]
EnvironmentFile=
EnvironmentFile=/opt/host/.mbf-env

ExecStartPre=/etc/systemd/system/script-esrf/host/starter-pre.sh
ExecStart=
ExecStart=/opt/os/bin/Starter %H
