# Computes tan^-1(2^-n) for CORDIC angle calculations.

import sys

import numpy as np

# Number of bits in tan inverse
BITS = 20
# Number of entries in the table
ROUNDS = 16

def generate_body():
    scale = 2**BITS / 2 / np.pi

    atan = np.arctan(2.**-(np.arange(ROUNDS)))
    result = np.int_(np.round_(scale * atan))

    for r in result[:-1]:
        print('        X"%05x",' % r)
    print('        X"%05x"' % result[-1])

print('''\
--
-- DO NOT EDIT THIS FILE !!!
--
-- This file has been automatically generated.
-- To change this file edit the source file and rebuild.
''')
for line in open(sys.argv[1]):
    if '@TABLE_BODY' in line:
        generate_body()
    else:
        print(line, end="")
