#!/bin/bash

PYTHONEXEC=/usr/bin/python3
if [ ! -f $PYTHONEXEC ]; then
    PYTHONEXEC=/usr/bin/python
fi

PYTHONVERS=$($PYTHONEXEC -c 'from __future__ import print_function; import sys; print(sys.version_info.major, sys.version_info.minor, sep="")')

if [ "$PYTHONVERS" = "27" ]; then
    PYTHON_MODULES_DIR=
elif [ "$PYTHONVERS" = "35" ]; then
    PYTHON_MODULES_DIR=/opt/os/epics/py35-modules/lib/python3.5/site-packages
elif [ "$PYTHONVERS" = "38" ]; then
    PYTHON_MODULES_DIR=/opt/os/epics/py38-modules
else
    echo "Python version not supported"
    exit 1
fi

if [ ! "$PYTHON_MODULES_DIR" = "" ]; then
    if [ -d "$PYTHON_MODULES_DIR" ]; then
        export PYTHONPATH=$PYTHON_MODULES_DIR:$PYTHONPATH
    else
        echo "directory $PYTHON_MODULES_DIR" does not exist
        exit 1
    fi
fi

SCRIPT_DIR=$(dirname $0)
$PYTHONEXEC $SCRIPT_DIR/mbf-control.py $@
