#!/bin/bash

# Script for loading FPGA onto machine.  Must be called on target system.

set -e

BIT_FILE=amc525_mbf.bit
while getopts 'f:h' option; do
    case "$option" in
        f)  BIT_FILE="$OPTARG" ;;
        h)  cat <<EOF
Usage: load_fpga [-f bit-file] addresses
    -f bit-file
        Optionally specify location of bit file, otherwise $BIT_FILE will
        be loaded from the current directory
EOF
            exit 0 ;;
        *)  echo >&2 'Invalid option: try -h for help'
            exit 1 ;;
    esac
done
shift $((OPTIND-1))

if (($# == 0)); then
    echo >&2 'Must specify addresses to load'
    exit 1
fi
AMC525_IPS=("$@")


# First of all ensure that nobody is trying to use the hardware before reloading
# the FPGA.  This avoids trouble during reset, as hot-plug is a bit fragile...
USERS="$(lsof -t /dev/amc525_mbf.* 2>/dev/null)" || true
[[ -n $USERS ]]  &&  kill -9 $USERS

SSH_OPTS='-o StrictHostKeyChecking=no'

for ip in "${AMC525_IPS[@]}"; do
    ip=192.168.40.$ip
    scp $SSH_OPTS "$BIT_FILE" root@$ip:/tmp/amc525_mbf.bit
    ssh -x $SSH_OPTS root@$ip amc525_lbtool fpga_load /tmp/amc525_mbf.bit
done
