#!/usr/bin/env python3

# Simple script to report interrupt events.

import os
import select
import struct


# Just using non-blocking as a test of select behaviour in the driver.
f = os.open('/dev/amc525_mbf.0.reg', os.O_NONBLOCK)

while True:
    r, w, x = select.select([f], [], [])
    mask = struct.unpack('I', os.read(f, 4))
    print('%08x' % mask)
